### PR TITLE
check http status codes

### PR DESCRIPTION
**Pull request by Emilv2**
Check http error codes and throw appropriate exceptions

### CODE REVIEW

**Comment by bollewolle** [comment]
Hi,
I see you made quite a few PR's to this repository, thanks for that. I currently don't have much time to review everything, but would you mind if I add you a Collaborator of this repository? I'm not that well know with Github to be honest, but I do believe you can merge the PR's yourself if you're sure about it.

Also, do note that there's some issues in Travis CI with regards to the code: https://travis-ci.com/github/bollewolle/pydelijn

This will mean that PIP is not updated, it only updates it when the checks in Travis CI are correct (I actually think it only checks Python 3.6 for the moment, so might have to change the .travis.yml file for it as well). 

Just let me know if you want to be added as Collaborator or not, it seems that you know what you're doing :) Otherwise it will be a while until I can verify the code myself.

Cheers!

**Comment by Emilv2** [comment]
Sure, sounds good to me :) I saw that some of the linting failed, but most of that was in your code so I did not touch it. Is it fine if I use the [black formatter](https://github.com/psf/black) on all the code?

**Comment by bollewolle** [comment]
I've added you as collaborator to this repository.
I was planning on adding the black formatter indeed as well, so feel free to add it. Or to optimise anything else of course.

**Comment by bollewolle** [comment]
Hi Emilv2,

Thanks for the commit!

Just so you know, as long as the TravisCI job fails the changes will not be pushed to pip.

For the jobs with errors check: https://travis-ci.com/github/bollewolle/pydelijn/builds/157034046 --> just click on the items under Linting that failed, you'll see the issues in the job details. Mostly it's because of lines being longer than 79 chars and some docstring that are missing or for which lines are not ending with a dot. But I think the errors speak for themselves.

Also note that for the push to pip to work when the jobs do pass you'll also need to update the version in setup.py. You could make it into 0.6.0 for example (and perhaps also add ""Programming Language :: Python :: 3.7"" to the classifiers while you're at it).

It's a bit of a hassle, took me a while to get it right, but it's one of the preferred methods it seems to keep the codebase structured.

Thanks!

**Comment by Emilv2** [comment]
Thanks for the info, I have made some pip packages with CI before so I think I'll be able to figure it out. If not I'll send you a message.

**Pull request merged**
